/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.92.1
  Forc version: 0.61.2
  Fuel-Core version: 0.31.0
*/

export type { TestContractAbi } from './TestContractAbi';

export { TestContractAbi__factory } from './factories/TestContractAbi__factory';
